### ISSUE TITLE
Trying to build targeting Mac Catalyst which requires nightly but a dependency fails

### ISSUE THREAD

**Issue by spullara** [getditto/safer_ffi#100]
If the use of mini_paste isn't too performance critical perhaps moving to paste would make sense since mini_paste hasn't been updated in a couple years.

```
   Compiling mini_paste v0.1.11
error[E0432]: unresolved imports `proc_macro::item`, `proc_macro::__expr_hack__`
  --> /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/mini_paste-0.1.11/src/lib.rs:11:5
   |
11 |     item as __item__,
   |     ----^^^^^^^^^^^^
   |     |
   |     no `item` in the root
   |     help: a similar name exists in the module: `iter`
12 |     __expr_hack__,
   |     ^^^^^^^^^^^^^ no `__expr_hack__` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `mini_paste` due to previous error
```

**Comment by danielhenrymantilla** [comment]
Yeah, with the current revamp/cleanup of `safer-ffi`, `minipaste` will be replaced back with `paste` (the reason for using it at the moment is a very weird and obscure misinteraction between spans of tokens and a `macro_rules!` macro calling a proc-macro which calls back a `macro_rules!` macro: in such a contrived scenario, the implementation of `mini_paste` seems to dodge the compiler bug whereas `paste` doesn't). 

But as the step #97 of the revamp is completed, we won't hit that bug anyways, making usage of `paste` fine again.

### Workaround

In the interim, you are hitting yet another compiler bug (can't have a renamed a `proc-macro = true` crate dependency when cross-compiling), which was circumvented [upstream](https://github.com/danielhenrymantilla/mini_paste/commit/69f4e5e0784d05fecaaca7ec8d8ed0a13f407472), but due to the "archived state" of `mini_paste` the workaround has not made it to crates.io:

```toml
# https://github.com/danielhenrymantilla/mini_paste/commit/69f4e5e0784d05fecaaca7ec8d8ed0a13f407472
[patch.crates-io.mini_paste]
git = "https://github.com/danielhenrymantilla/mini_paste.git"
rev = "69f4e5e0784d05fecaaca7ec8d8ed0a13f407472"
```
